-- MySQL Script generated by MySQL Workbench
-- Tue Oct 23 22:47:03 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_vales
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_vales
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_vales` DEFAULT CHARACTER SET utf8 ;
USE `db_vales` ;

-- -----------------------------------------------------
-- Table `tab_persons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tab_persons` ;

CREATE TABLE IF NOT EXISTS `tab_persons` (
  `id_person` INT(11) NOT NULL AUTO_INCREMENT,
  `des_person` VARCHAR(64) NOT NULL,
  `des_email` VARCHAR(128) NULL,
  `nr_phone` BIGINT(20) NULL,
  `des_pis` VARCHAR(11) NOT NULL,
  `des_cpf` VARCHAR(11) NOT NULL,
  `des_rg` VARCHAR(15) NULL,
  `num_salario` DECIMAL(10,2) NOT NULL,
  `dt_register` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dt_change` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_person`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tab_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tab_users` ;

CREATE TABLE IF NOT EXISTS `tab_users` (
  `id_user` INT(11) NOT NULL AUTO_INCREMENT,
  `id_person` INT(11) NOT NULL,
  `des_login` VARCHAR(64) NOT NULL,
  `des_password` VARCHAR(256) NOT NULL,
  `inadmin` TINYINT(4) NOT NULL,
  `dt_register` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_user`),
  CONSTRAINT `FK_users_persons`
    FOREIGN KEY (`id_person`)
    REFERENCES `tab_persons` (`id_person`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_users_persons_idx` ON `tab_users` (`id_person` ASC);


-- -----------------------------------------------------
-- Table `tab_vouchersstatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tab_vouchersstatus` ;

CREATE TABLE IF NOT EXISTS `tab_vouchersstatus` (
  `id_status` INT(11) NOT NULL AUTO_INCREMENT,
  `des_status` VARCHAR(64) NOT NULL,
  `dt_register` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tab_vouchers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tab_vouchers` ;

CREATE TABLE IF NOT EXISTS `tab_vouchers` (
  `id_voucher` INT(11) NOT NULL AUTO_INCREMENT,
  `id_user` INT(11) NOT NULL,
  `id_status` INT(11) NOT NULL,
  `int_valor` SMALLINT(5) NOT NULL,
  `dt_register` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_voucher`),
  CONSTRAINT `fk_tab_vouchers_tab_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `tab_users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tab_vouchers_tab_vouchersstatus1`
    FOREIGN KEY (`id_status`)
    REFERENCES `tab_vouchersstatus` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tab_vouchers_tab_users1_idx` ON `tab_vouchers` (`id_user` ASC);

CREATE INDEX `fk_tab_vouchers_tab_vouchersstatus1_idx` ON `tab_vouchers` (`id_status` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
